### ISSUE TITLE
Does not work even if CSS file are updated

### ISSUE THREAD

**Issue by FPierre** [Itz-Abhishek-Tiwari/pop-os-dock-application-color-changer#2]
Hi, I've used the script, that have updated the CSS files

```css
/* /usr/share/gnome-shell/extensions/pop-cosmic@system76.com/dark.css */
.cosmic-applications-dialog {
background-color: rgba(26,30,36,0.8);
       box-shadow: 0 2px 4px 2px rgba(0,0,0,0.1);
}

.cosmic-applications-icon {
       color: #9b9b9b;
}

.cosmic-applications-folder-title {
       color: white;
}

.cosmic-applications-available {
       color: white;
}

.cosmic-folder-edit-button {
        background: #353535;
}

.cosmic-folder-edit-button:hover {
        background: #484848;
}
```

but it does not change the background color and opacity
I use `Pop!_OS 22.04 LTS` on Kernel `6.2.6-76060206-generic` with `X11`
